<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 18 Nov 2017 13:12:46 +0000
 */
$conf['title'] = 'WikiName';
$conf['template'] = 'bootstrap3';
$conf['lang'] = 'en';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['userewrite'] = 1;
$conf['useslash'] = 1;

// end auto-generated content
