<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Sat, 18 Nov 2017 13:12:46 +0000
 */
$conf['breadcrumbs'] = 0;
$conf['dformat'] = '%Y-%m-%d %H:%M';
$conf['disableactions'] = 'register';
$conf['lang'] = 'en';
$conf['license'] = '0';
$conf['template'] = 'bootstrap3';
$conf['title'] = 'WikiName';
$conf['useacl'] = 1;
$conf['userewrite'] = 1;
$conf['useslash'] = 1;
$conf['youarehere'] = 1;
$conf['superuser'] = '@admin';
$conf['tpl']['bootstrap3']['fixedTopNavbar'] = 1;
$conf['tpl']['bootstrap3']['showEditBtn'] = 'logged';
$conf['tpl']['bootstrap3']['showLandingPage'] = 1;
$conf['tpl']['bootstrap3']['bootstrapTheme'] = 'bootswatch';
$conf['tpl']['bootstrap3']['bootswatchTheme'] = 'cerulean';

// end auto-generated content
